#!/usr/bin/env python3
"""tools/mcp/floodconnect_mcp.py -- FloodConnect MCP server (Component B).

Stdio MCP server exposing FloodConnect's local API v1 export (Component A,
tools/api/export_api.py -> site/dist/api/v1/**) to an external AI assistant.
Local files only (project decision 2026-10-04, no-hosted-access): this repo ships
no pre-computed export and no hosted/remote FLOODCONNECT_API_BASE is accepted --
strictly read-only, no tool writes, no collect.py invocation, no network call of
any kind. The export is generated by the installer on their own machine; a
missing export returns OPEN with a "run refresh locally" action instead.

Core logic lives in plain functions (`list_areas`, `get_area_state`, ...)
that take an explicit `base` argument, so tests can call them directly
without spinning up a transport. The `@mcp.tool()`-decorated wrappers at the
bottom read FLOODCONNECT_API_BASE once and delegate to those functions --
this is also where the shared `_with_epistemic_envelope` helper is applied,
so no single tool can forget it.

Falls back to a minimal stdlib JSON-RPC responder if the `mcp` package is not
importable, so this degrades rather than hard-fails in an environment
without the SDK (spec sec. 3.2).
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import community_dag  # noqa: E402 -- the single canonical route function (AI.md section 2)

# This used to be the bare relative string
# "site/dist/api/v1", resolved against the MCP CLIENT's own current working
# directory (whatever launched this stdio process), not this repo. An MCP client
# almost never has THIS repo as its cwd, so `_resolve_base()` silently pointed at a
# nonexistent path on a fresh clone. Anchoring to `_REPO_ROOT` (this file's own
# location, three levels up) makes the default correct regardless of the caller's
# cwd. This repo ships NO pre-computed export -- the path below does not exist
# until the installer runs collect.py --all, site/build_data.py and
# tools/api/export_api.py on their own machine (or calls `floodconnect_answer`,
# which reads data/observations.sqlite directly and refreshes by default); until
# then every tool here returns OPEN with that same instruction. An explicit
# `FLOODCONNECT_API_BASE` env override may only be a local path -- a hosted/remote
# URL is refused (see `_read()` below, project decision 2026-10-04).
DEFAULT_BASE = str(_REPO_ROOT / "site" / "dist" / "api" / "v1")

# The rule TEXT lives in exactly one place -- AI.md's
# "Mandatory reasoning rules" section -- never duplicated as a second local
# constant here. `explain_rules()` below loads that section at runtime
# instead. The fixed five-value tag vocabulary is also stated once, in
# AI.md's compute-call section, and imported from the single shared
# tag_vocabulary module (see that file's docstring) -- never redeclared here.
from tag_vocabulary import TAG_VOCABULARY  # noqa: E402 -- _REPO_ROOT is already on sys.path
_AI_MD_PATH = _REPO_ROOT / "AI.md"
_RULES_SECTION_MARKER = "## Mandatory reasoning rules"


def _load_rules_text_from_ai_md() -> str | None:
    """Reads AI.md's rules section at call time rather than caching a
    second copy -- if AI.md moves or is renamed, this degrades to None
    (surfaced as tag: OPEN below) instead of silently going stale."""
    try:
        text = _AI_MD_PATH.read_text(encoding="utf-8")
    except OSError:
        return None
    start = text.find(_RULES_SECTION_MARKER)
    if start == -1:
        return None
    rest = text[start:]
    end = rest.find("\n## ", len(_RULES_SECTION_MARKER))
    return rest[:end].strip() if end != -1 else rest.strip()


class FloodConnectMCPError(Exception):
    """Typed error -- carries a code, never raw exception text that could
    leak a local path. Caught at the tool boundary and turned into a typed
    response, not an uncaught exception reaching the transport."""

    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


def _with_epistemic_envelope(payload: dict, source: str, observed_at: str | None, tag: str) -> dict:
    """Shared response-wrapper (spec sec. 3.3): every tool response carries
    source/observed_at (staleness)/tag -- applied here once so it can't be
    forgotten in one tool and not another."""
    return {
        **payload,
        "source": source,
        "staleness": {"observed_at": observed_at, "tag": tag},
    }


def _read_local(base: Path, rel_path: str) -> Any:
    p = base / rel_path
    if not p.exists():
        raise FloodConnectMCPError("NOT_FOUND", f"no such published file: {rel_path}")
    return json.loads(p.read_text(encoding="utf-8"))


def _read(base: str, rel_path: str) -> Any:
    # Project decision 2026-10-04 (no-hosted-access): this server reads ONLY a local
    # export the caller generated on their own machine. An http(s) FLOODCONNECT_API_BASE
    # used to fetch someone else's hosted copy with a single GET -- that is itself a
    # hosted-access channel, which the ruling removes. A URL base is now refused
    # outright: OPEN, with the same "run refresh locally" action every other missing-export
    # path returns, never a network fetch.
    if base.startswith("http://") or base.startswith("https://"):
        raise FloodConnectMCPError(
            "OPEN",
            "FLOODCONNECT_API_BASE must be a local path -- hosted/remote export access "
            "is disabled by project decision; run 'floodconnect answer --refresh' (or "
            "collect.py --all + site/build_data.py + tools/api/export_api.py) on your "
            "own machine instead.",
        )
    return _read_local(Path(base), rel_path)


def _resolve_base() -> str:
    return os.environ.get("FLOODCONNECT_API_BASE", DEFAULT_BASE)


# ---------------------------------------------------------------------------
# Build-time snapshot staleness fix (2026-10-04): `site/dist/api/v1/areas/<id>.json` is a
# point-in-time BUILD-TIME snapshot -- its own `data_freshness`/`staleness`/
# `age_class` fields were computed once, when `site/build_data.py` last ran, and then
# committed/redeployed unchanged on every later push. MEASURED later
# via a real MCP client ~30 hours after that build: `get_area_state` still
# reported `age_class: "fresh"`/`stale: false` on a canal reading that was by then a
# day and a half old, and `forward_hazard` still read as an un-dated, un-staled
# "ฝนกำลังจะเบาลงหลัง 22:00 น." narrative. Every staleness field this tool returns is
# now RECOMPUTED against the REAL wall-clock call time below, never trusted from the
# file as-is -- the baked fields are still read (as the `observed_at` input), just
# never taken as the final verdict.
# ---------------------------------------------------------------------------
import datetime as _dt  # noqa: E402

import live_water_level as _lwl  # noqa: E402 -- the ONE freshness gate, see its own module docstring

_MCP_RECOMPUTE_FUTURE_TOLERANCE_H = -1.0  # real wall-clock call time, same default as
                                           # `lwl.is_fresh`'s own (see live_water_level.py)


def _recompute_staleness(observed_at: "str | None", max_age_h: float = _lwl.STALE_HOURS) -> dict:
    """Recompute `{observed_at, age_h, age_class, stale, tag}` against the REAL
    wall-clock call time -- never the file's own baked `generated_at_bkk`/age fields.
    `age_class` mirrors `site/build_data.py:age_class` (fresh|stale|expired) without
    importing that module (it is not on the MCP server's own dependency path and pulls
    in the full collect.py stack) -- same STALE_HOURS cutoff, same `lwl.age_hours`."""
    now_iso = _dt.datetime.now(_dt.timezone.utc).isoformat()
    fresh, age_h = _lwl.is_fresh(observed_at, now_iso, max_age_h,
                                  future_tolerance_h=_MCP_RECOMPUTE_FUTURE_TOLERANCE_H)
    if age_h is None:
        age_class = "expired"
    elif not fresh:
        age_class = "stale"
    else:
        age_class = "fresh"
    return {
        "observed_at": observed_at,
        "age_h": age_h,
        "age_class": age_class,
        "stale": age_class != "fresh",
        "tag": "MEASURED" if age_class != "expired" else "OPEN",
        "recomputed_at": now_iso,
    }


# Stale forward_hazard field drop (2026-10-04): the fields a stale forward_hazard must
# drop -- every one the a later audit MEASURED as still present on a 31h-old
# snapshot (`forecast.available`, `direction`, `trend_word`, `next*_mm`, undated
# `items`/`hourly`/`hourly_full`). `available`/`status` are set to a stale-aware
# value below rather than left in this list, since callers branch on them.
_STALE_FORECAST_FIELDS = (
    "direction", "trend_word", "next6h_mm", "next24h_mm", "h24_48_mm", "h48_72_mm",
    "first_dry_6h_start", "items", "hourly", "hourly_full",
)
_STALE_FORECAST_72H_FIELDS = ("value_mm", "model_id", "model_th")
# The layer0 in/out rows carry the SAME forecast prose baked as free text
# (`text_th`, e.g. "พรุ่งนี้ 2 มม. · รวม 7 วัน 68 มม."), tagged by the one shared
# provenance label third-party forecast rows always use (`tag_th`). Suppressing by
# that tag, not by `label_th` guesswork, catches every model row without a second
# hard-coded model-name list.
_LAYER0_FORECAST_TAG_TH = "ข่าว/บุคคลที่สาม"
_STALE_TEXT_TH = "[STALE -- ตัวเลขพยากรณ์เก่าถูกระงับ, รัน floodconnect_answer --refresh เพื่อดูค่าสด]"


def _null_stale_forecast_block(fh_forecast: dict, age_text: str) -> None:
    """Mutates one forecast-shaped dict in place (`forward_hazard.forecast` or
    `.forecast_short`, which share the same shape) so every forward-looking
    figure/word is suppressed, while `source`/`trust_tier`/`fetched_at` survive
    so a caller can still see there WAS a forecast and when it was captured."""
    for key in _STALE_FORECAST_FIELDS:
        if key in fh_forecast:
            fh_forecast[key] = None
    fh_forecast["available"] = False
    fh_forecast["status"] = f"STALE snapshot ({age_text} old) -- figures suppressed"


def _recompute_area_freshness(area: dict) -> dict:
    """Walk the one real snapshot shape (`current_local_state.water_balance.staleness`,
    `current_local_state.canals[].staleness`, `forward_hazard`) and overwrite every
    staleness field with `_recompute_staleness`'s live result. Returns a NEW dict
    (never mutates the caller's `area`, which a test may still hold a reference to).

    This fix: staleness of the FORECAST is judged by the forecast's
    own `fetched_at` (when present), never by the whole area's `generated_at_bkk` --
    those two can legitimately differ (a forecast source can fail a refresh while
    everything else in the area succeeds, or vice versa). When stale, every
    forward-looking figure is nulled IN THE DATA -- `forward_hazard.forecast`,
    `.forecast_short`, `.forecast_72h_worst`, and the layer0 in/out rows' own
    third-party-forecast `text_th` strings and `prop_flood_06.forecast_72h_worst_*`
    -- not only suppressed by a CLI print statement."""
    import copy
    out = copy.deepcopy(area)
    cls = out.get("current_local_state") or {}
    wb = cls.get("water_balance")
    if isinstance(wb, dict):
        baked = wb.get("staleness") or {}
        wb["staleness"] = _recompute_staleness(baked.get("observed_at"))
    for canal in cls.get("canals") or []:
        if not isinstance(canal, dict):
            continue
        baked = canal.get("staleness") or {}
        canal["staleness"] = _recompute_staleness(baked.get("observed_at"))

    # 2026-10-04 fix: computed here (not only at the bottom, as
    # before) so the layer0 measured-row marking just below can use it too.
    all_classes = [wb["staleness"]["age_class"]] if isinstance(wb, dict) else []
    all_classes += [c["staleness"]["age_class"] for c in (cls.get("canals") or [])
                    if isinstance(c, dict)]
    order = {"fresh": 0, "stale": 1, "expired": 2}
    overall = max(all_classes, key=lambda c: order.get(c, 2)) if all_classes else "expired"

    # 2026-10-04 fix: a layer0 MEASURED-tagged row (e.g. "ฝนวัดจริง
    # (24 ชม.) 0.0 มม.", tag_th="วัดจากไฟล์ข้อมูล") used to keep that tag unchanged
    # forever -- only the separately-tagged third-party-forecast rows
    # (`_LAYER0_FORECAST_TAG_TH`) got any staleness treatment at all. A measured row
    # has no freshness timestamp of its own in this exported shape either, so (same
    # reasoning as the tier fix above) it inherits the area's own overall
    # water_balance/canals staleness, never a value read as current when the whole
    # area snapshot is already stale/expired.
    if overall != "fresh":
        layer0_for_measured = cls.get("layer0") if isinstance(cls.get("layer0"), dict) else None
        if layer0_for_measured:
            for items_key in ("in_items", "out_items"):
                for row in layer0_for_measured.get(items_key) or []:
                    if (isinstance(row, dict)
                            and row.get("tag_th") not in (_LAYER0_FORECAST_TAG_TH, None)
                            and row.get("tag_th") != "ยังไม่มีคำตอบ"):  # OPEN rows have nothing to mark stale
                        row["stale"] = True
                        row["text_th"] = f"{row.get('text_th', '')} [STALE: {overall}]"

    fh = out.get("forward_hazard")
    fh_stale = True
    age_text = "age unknown"
    if isinstance(fh, dict):
        forecast = fh.get("forecast") if isinstance(fh.get("forecast"), dict) else {}
        forecast_fetched_at = forecast.get("fetched_at")
        fresh_info = _recompute_staleness(
            forecast_fetched_at if forecast_fetched_at else out.get("generated_at_bkk"),
            max_age_h=_lwl.STALE_HOURS,
        )
        fh["recomputed_staleness"] = fresh_info
        fh_stale = fresh_info["stale"]
        age_text = f"{fresh_info['age_h']:.1f}h" if fresh_info["age_h"] is not None else "age unknown"
        if fh_stale:
            # Note: a stale forward-hazard narrative must not read as a
            # current trend -- drop the prose/figures IN THE DATA (every reader of
            # this dict, not only the CLI's own printer), keep the fact that a
            # forecast existed and when it was generated.
            if isinstance(fh.get("forecast"), dict):
                _null_stale_forecast_block(fh["forecast"], age_text)
            if isinstance(fh.get("forecast_short"), dict):
                _null_stale_forecast_block(fh["forecast_short"], age_text)
            worst = fh.get("forecast_72h_worst")
            if isinstance(worst, dict):
                for key in _STALE_FORECAST_72H_FIELDS:
                    if key in worst:
                        worst[key] = None
            fh["note"] = ("stale snapshot ({} old) -- narrative/figures suppressed, "
                           "re-run `floodconnect_answer`/`--refresh` for a live hazard "
                           "read").format(age_text)

            layer0 = cls.get("layer0") if isinstance(cls.get("layer0"), dict) else None
            if layer0:
                for items_key in ("in_items", "out_items"):
                    for row in layer0.get(items_key) or []:
                        if isinstance(row, dict) and row.get("tag_th") == _LAYER0_FORECAST_TAG_TH:
                            row["text_th"] = _STALE_TEXT_TH
                pf06 = layer0.get("prop_flood_06")
                if isinstance(pf06, dict):
                    pf06["forecast_72h_worst_text_th"] = _STALE_TEXT_TH
                    pf06["forecast_72h_worst_value_mm"] = None
                    pf06["forecast_72h_worst_model_th"] = None
                    pf06["forecast_72h_items_th"] = None

    # 2026-10-04 fix: `layer0.prop_flood_06.tier`/`tier_color`/
    # `tier_word_th` were baked at build time and never recomputed at MCP-call time --
    # a caller could be served a RED tier colour from a build that is now hours/days
    # old, with no staleness flag on the colour itself (only the unrelated forecast
    # sub-fields got this treatment). Gated on the SAME overall water_balance/canals
    # age_class computed just above -- the tier figure has no freshness timestamp of
    # its own in the exported shape, so it inherits the area's own staleness, never a
    # second, independently-invented cutoff.
    if overall != "fresh":
        pf06_tier = (cls.get("layer0") or {}).get("prop_flood_06") \
            if isinstance(cls.get("layer0"), dict) else None
        if isinstance(pf06_tier, dict):
            pf06_tier["tier_word_th"] = _STALE_TEXT_TH
            pf06_tier["tier_color"] = None
            pf06_tier["tier_stale"] = True
            pf06_tier["tier_stale_note"] = (
                f"tier baked at build time ({overall}), never recomputed against this "
                "run's own wall-clock -- re-run `floodconnect_answer`/`--refresh` for a "
                "live tier read")

    out["data_freshness"] = {
        "overall_age_class": overall,
        "oldest_field": None,
        "computed_via": "recomputed at MCP call time against real wall-clock now "
                         "(recompute fix) -- never the baked build-time snapshot value",
        "recomputed_at": _dt.datetime.now(_dt.timezone.utc).isoformat(),
    }
    out["snapshot"] = True
    out["snapshot_generated_at"] = area.get("generated_at_bkk")
    return out


# ---------------------------------------------------------------------------
# Core tool logic (plain functions, base explicit -- directly testable)
# ---------------------------------------------------------------------------

# No-hosted-access change (2026-10-04, project decision): this repo ships NO
# pre-computed `site/dist/api/v1/**` export any more (not tracked in git, not part of
# any release). A caller who has not yet run the local export pipeline on their own
# machine gets an honest UNKNOWN + a concrete next_action here, never a bare
# protocol-level error and never a value read from a shipped snapshot.
_RUN_EXPORT_ACTION = (
    "no local export found under FLOODCONNECT_API_BASE -- run 'collect.py --all' then "
    "'python3 site/build_data.py' then 'python3 tools/api/export_api.py "
    "--data-json site/dist/data.json --typology-graph output/typology_graph.json "
    "--typology-subgraph-dir output --self-help-dag site/inputs/community/"
    "self_help_dag.yaml --sources-registry sources/registry.yaml --out-dir "
    "site/dist/api/v1' on your own machine, network and keys -- or call "
    "floodconnect_answer instead, which reads data/observations.sqlite directly."
)


def _known_area_ids() -> "list[str]":
    """Reuses `kb.py`'s own `_ANSWER_AREAS` keys (never a second hard-coded area
    list) so `get_area_state` can tell a genuinely unknown area_id apart from a
    known one whose export just hasn't been generated locally yet."""
    try:
        import kb as kb_mod
        return sorted(kb_mod._ANSWER_AREAS)
    except Exception:  # pragma: no cover - defensive, kb.py must not be required to import
        return []


def list_areas(base: str) -> dict:
    try:
        index = _read(base, "index.json")
    except FloodConnectMCPError:
        return _with_epistemic_envelope(
            {"areas": [], "next_action": _RUN_EXPORT_ACTION},
            source="index.json", observed_at=None, tag="OPEN",
        )
    areas = []
    for area_id in index.get("areas", []):
        try:
            area = _read(base, f"areas/{area_id}.json")
            areas.append({"area_id": area_id, "label": area.get("label")})
        except FloodConnectMCPError:
            areas.append({"area_id": area_id, "label": None})
    return _with_epistemic_envelope(
        {"areas": areas}, source="index.json",
        observed_at=index.get("generated_at_utc"), tag="MEASURED",
    )


def get_area_state(base: str, area_id: str) -> dict:
    try:
        area = _read(base, f"areas/{area_id}.json")
    except FloodConnectMCPError:
        if area_id in _known_area_ids():
            # A known area with no local export yet -- UNKNOWN + refresh action,
            # never an error that reads as "this place doesn't exist".
            # 2026-10-04 fix: the old return only had `next_action` +
            # the envelope's `tag: OPEN` -- a caller reading only the fields every
            # OTHER `get_area_state` response has (`current_local_state`/
            # `forward_hazard`) saw neither key at all, never an explicit UNKNOWN.
            return _with_epistemic_envelope(
                {"area_id": area_id, "current_local_state": "UNKNOWN",
                 "forward_hazard": "UNKNOWN", "next_action": _RUN_EXPORT_ACTION},
                source=f"areas/{area_id}.json", observed_at=None, tag="OPEN",
            )
        raise FloodConnectMCPError("AREA_NOT_FOUND", f"unknown area_id: {area_id!r}")
    # Recompute fix: recompute every staleness/age_class field against the real
    # wall-clock call time before building the payload below -- see
    # `_recompute_area_freshness`'s own docstring for why the baked file values are
    # never trusted directly.
    area = _recompute_area_freshness(area)
    current_local_state = area.get("current_local_state")
    # FIX B item 4 (2026-10-04): `water_balance` (PROP-FLOOD-03) REFUSES for every
    # served area today -- both village *.balance.yaml declare A/c/C_pump/S0 as OPEN
    # (see `site/build_data.py::build_village_water_balance`'s own docstring), so a
    # caller reading only `status: REFUSED`/`reason_codes` here had no plain-language
    # pointer to what DOES exist. Say so plainly and point at `floodconnect_answer`,
    # never silently leave the caller with a bare REFUSED and no next step.
    if isinstance(current_local_state, dict):
        wb = current_local_state.get("water_balance")
        if isinstance(wb, dict) and wb.get("status") == "REFUSED":
            wb["note"] = (
                "water_balance (PROP-FLOOD-03) is not computed in v0.1.x -- both "
                "served villages declare A/c/C_pump/S0 as OPEN, so this always "
                "REFUSES by design, not a bug; call floodconnect_answer instead for a "
                "real computed reading (state/hazard/accountability/next_action)."
            )
    payload = {
        "area_id": area.get("area_id"),
        "label": area.get("label"),
        "current_local_state": current_local_state,
        "forward_hazard": area.get("forward_hazard"),
        "contradictions": area.get("contradictions", []),
        "safety": area.get("safety"),
        "data_freshness": area.get("data_freshness"),
        # FIX B (2026-10-04): carry the recomputed snapshot markers into the
        # payload itself -- a caller reading only `payload` (not the intermediate
        # `area` dict) must still be able to see this is a retained snapshot and
        # when it was generated, same as `_recompute_area_freshness` sets them.
        "snapshot": area.get("snapshot"),
        "snapshot_generated_at": area.get("snapshot_generated_at"),
    }
    tag = (area.get("data_freshness") or {}).get("overall_age_class")
    tag = {"fresh": "MEASURED", "stale": "MEASURED", "expired": "OPEN"}.get(tag, "OPEN")
    return _with_epistemic_envelope(
        payload, source=f"areas/{area_id}.json",
        observed_at=area.get("generated_at_bkk"), tag=tag,
    )


def get_station(base: str, code: str) -> dict:
    """UNKNOWN is never SAFE (spec sec. 3.3): a code not found anywhere
    returns {"found": false, "tag": "OPEN"}, never a bare false/null and
    never inferred as 'no flooding'."""
    index = _read(base, "index.json")
    for area_id in index.get("areas", []):
        try:
            area = _read(base, f"areas/{area_id}.json")
        except FloodConnectMCPError:
            continue
        # Recompute fix: same live recompute as `get_area_state` -- a station's baked
        # `staleness.age_class`/`tag` must never be trusted as of the real call time.
        area = _recompute_area_freshness(area)
        for canal in (area.get("current_local_state") or {}).get("canals", []):
            if canal.get("station_code") == code:
                return _with_epistemic_envelope(
                    {"found": True, "area_id": area_id, "station": canal},
                    source=f"areas/{area_id}.json",
                    observed_at=canal.get("staleness", {}).get("observed_at"),
                    tag=canal.get("staleness", {}).get("tag", "OPEN"),
                )
    return {
        "found": False,
        "tag": "OPEN",
        "source": "index.json + areas/*.json",
        "staleness": {"observed_at": None, "tag": "OPEN"},
    }


def get_typology_subgraph(base: str, area_id: str) -> dict:
    try:
        sub = _read(base, f"typology/subgraph/{area_id}.json")
    except FloodConnectMCPError:
        raise FloodConnectMCPError("AREA_NOT_FOUND", f"no typology subgraph for area_id: {area_id!r}")
    return _with_epistemic_envelope(
        sub, source=f"typology/subgraph/{area_id}.json",
        observed_at=sub.get("generated_at_bkk"), tag="RELAYED",
    )


def find_safe_route(base: str, zone_id: str, mode: str, group_size: int) -> dict:
    """Maps the exported `community/self_help_dag.json` snapshot onto
    `community_dag.find_safe_route` -- the single canonical route function
    (AI.md section 2: "never re-implemented"). This tool performs no routing
    logic of its own: it only builds the doc the canonical function expects
    and translates its `RouteResult` into the MCP envelope. A partially-
    verified route is never returned silently (spec sec. 3.3); an UNSAFE or
    stale node is rejected by the canonical function's own hard constraints,
    not by anything re-derived here."""
    dag = _read(base, "community/self_help_dag.json")
    doc = {"nodes": dag.get("nodes") or {}, "edges": dag.get("edges") or []}
    observed_at = dag.get("generated_at_bkk")

    result = community_dag.find_safe_route(
        doc, zone_id, mode=mode, group_size=group_size,
    )

    if not result.found:
        return {
            "result": "NO_FEASIBLE_SAFE_ROUTE",
            "reason": result.reason,
            "checked_nodes": list(result.path),
            "source": "community/self_help_dag.json",
            "staleness": {"observed_at": observed_at, "tag": "OPEN"},
        }

    return _with_epistemic_envelope(
        {"result": "ROUTE_FOUND", "path": list(result.path), "target": result.target,
         "checked_nodes": list(result.path), "mode": mode, "group_size": group_size},
        source="community/self_help_dag.json",
        observed_at=observed_at, tag="MEASURED",
    )


def list_upstream_sources(base: str, agency: str | None = None) -> dict:
    sources = _read(base, "sources.json")
    rows = sources.get("sources", [])
    if agency:
        needle = agency.lower()
        rows = [s for s in rows
                if needle in (s.get("agency_en") or "").lower()
                or needle in (s.get("agency_th") or "").lower()]
    return _with_epistemic_envelope(
        {"sources": rows}, source="sources.json", observed_at=None, tag="RELAYED",
    )


def floodconnect_answer_core(at: str, refresh: "bool | None" = None,
                              offline: bool = False, verbose: bool = False) -> dict:
    """The MCP equivalent of `floodconnect answer --refresh` -- every OTHER tool here
    reads the static `site/dist/api/v1` export (Component A), but this one runs the
    richer compute call (state + hazard + accountability + next_action + cctv +
    source_tags, AI.md's one compute call) and its on-demand refresh directly. `cctv`
    (added 2026-10-04, F8) lists up to 3 nearest CCTV cameras, tagged `VISUAL-CHECK` --
    a human-look-yourself reference, never an input to `state`/`hazard`/`next_action`'s
    own classification. This imports `kb` directly (it is on
    `sys.path` via `_REPO_ROOT`, inserted at module load above) and calls
    `kb.build_answer` in-process -- the SAME function `floodconnect answer`'s own
    `cmd_answer` CLI calls, never a second implementation. ONE GET per relevant source,
    on THIS machine's own network/keys (never ours), no scheduler, no retry loop -- see
    `kb._refresh_relevant_sources` and the self-install project decision. A bad `at`
    raises `kb._BadAt`; this wraps that into the same typed `FloodConnectMCPError`
    every other tool here uses, instead of leaking a raw traceback to the MCP
    transport.

    Refresh-by-default (project decision 2026-10-03): when `refresh` is left at its
    default (`None`), this fetches the relevant wired sources before computing UNLESS
    `offline=True` -- same policy as `floodconnect answer` (CLI). Passing `refresh`
    explicitly (`True`/`False`) keeps the old opt-in behaviour for backward
    compatibility with existing callers that already decide for themselves; `offline`
    is then ignored."""
    import kb  # noqa: E402 -- _REPO_ROOT is already on sys.path (see module top)
    effective_refresh = (not offline) if refresh is None else refresh
    try:
        return kb.build_answer(at, refresh=effective_refresh, verbose=verbose)
    except kb._BadAt as e:
        raise FloodConnectMCPError("BAD_AT", str(e)) from e


def floodconnect_locate_core(at: str, province: "str | None" = None) -> dict:
    """The MCP equivalent of `floodconnect locate --at lat,lon [--province X]`
    (M4, "KG-first that AIs cannot skip"). Offline, reads only
    `output/kg_index/` -- no network, no graphml read, <3s. Resolves `at` to
    its province (from `province`, the CALLER's own geocoding decision, or up
    to 3 RELAYED candidates when omitted), nearest sub-basin(s)/assets/reach,
    stations, agencies, known_gaps, and a compact `kg_anchor`. A bad `at`
    raises the same typed `FloodConnectMCPError` every other tool here uses;
    a missing `output/kg_index/` raises `MISSING_KG_INDEX` rather than
    guessing."""
    from tools.kg.locate import KGIndexMissing, locate as _locate

    try:
        lat_s, lon_s = at.split(",")
        lat, lon = float(lat_s), float(lon_s)
    except ValueError as e:
        raise FloodConnectMCPError("BAD_AT", f"--at must be 'lat,lon', got {at!r}") from e
    try:
        return _locate(lat, lon, province=province)
    except KGIndexMissing as e:
        raise FloodConnectMCPError("MISSING_KG_INDEX", str(e)) from e


def explain_rules(base: str | None = None) -> dict:
    """Returns the fixed epistemic rules this server enforces, loaded from
    AI.md's "Mandatory reasoning rules" section at call time -- not a
    second hard-coded copy. `rules_text` carries
    the actual wording verbatim; `tag_vocabulary` is the fixed five-value
    set stated once in AI.md's compute-call section (any finer distinction
    such as "this MEASURED value is graph-derived" is a `basis` key
    alongside the tag, never a sixth tag value -- see
    skills/floodconnect/references/epistemic_rules.md)."""
    rules_text = _load_rules_text_from_ai_md()
    return {
        "rules_text": rules_text,
        "tag_vocabulary": list(TAG_VOCABULARY),
        "unknown_is_not_safe": (
            "UNKNOWN is not SAFE. current_local_state and forward_hazard are "
            "independent — a calm current reading does not cancel an active "
            "forecast hazard."
        ),
        "source": "AI.md#mandatory-reasoning-rules",
        "staleness": {"observed_at": None, "tag": "VERIFIED" if rules_text else "OPEN"},
    }


# ---------------------------------------------------------------------------
# MCP transport wiring
# ---------------------------------------------------------------------------

_TOOL_DESCRIPTION_SUFFIX = (
    " UNKNOWN is not SAFE. current_local_state and forward_hazard are "
    "independent — a calm current reading does not cancel an active "
    "forecast hazard."
)

# First-contact descriptions (founder ruling 2026-10-04: "the FIRST thing any AI
# touches... is the most important surface") for the stdlib JSON-RPC fallback's
# `tools/list` response -- used ONLY in the `except ImportError` branch below, where
# `_TOOLS` maps each tool name to a bare lambda (no `__doc__` of its own), so the old
# `fn.__doc__ or ""` read came back empty for every single tool. The real `mcp` SDK
# path above does not need this: its `@mcp.tool()` wrappers each carry their own
# docstring, which FastMCP reads directly. Each entry here is one plain sentence
# naming what the tool returns, plus the shared reminder that every value is computed
# on the caller's own machine and is never an official reading.
_TOOL_DESCRIPTIONS: dict[str, str] = {
    "floodconnect_list_areas": (
        "List every area this installation's local export covers (currently "
        "Sammakorn, Ram53), computed on your own machine -- not an official source."
        + _TOOL_DESCRIPTION_SUFFIX),
    "floodconnect_get_area_state": (
        "Full current_local_state + forward_hazard for one area, computed on your "
        "own machine from your own local export -- not an official reading."
        + _TOOL_DESCRIPTION_SUFFIX),
    "floodconnect_get_station": (
        "Look up one canal/water-level station code across all covered areas, from "
        "your own local export -- not an official reading." + _TOOL_DESCRIPTION_SUFFIX),
    "floodconnect_get_typology_subgraph": (
        "Typology subgraph (nodes/edges) for one area, from your own local export."
        + _TOOL_DESCRIPTION_SUFFIX),
    "floodconnect_find_safe_route": (
        "Walk the self-help DAG for a verified, fresh route from a zone_id, computed "
        "on your own machine -- never an evacuation order." + _TOOL_DESCRIPTION_SUFFIX),
    "floodconnect_list_upstream_sources": (
        "List the upstream government/agency source-registry entries this project "
        "reads from, optionally filtered by agency." + _TOOL_DESCRIPTION_SUFFIX),
    "floodconnect_explain_rules": (
        "Return the fixed epistemic rules this server enforces (from AI.md), so a "
        "caller can check its own behaviour against them." + _TOOL_DESCRIPTION_SUFFIX),
    "floodconnect_answer": (
        "Compute a full flood/canal/pump/tide readout for one area on THIS machine "
        "(fetching fresh sources by default, on your own network/keys) -- nothing is "
        "hosted, and no reading here is an official warning." + _TOOL_DESCRIPTION_SUFFIX),
    "floodconnect_locate": (
        "KG-first step (M4): resolve a lat,lon point to its province/sub-basin/"
        "nearest assets/reach/stations/agencies/known_gaps + kg_anchor, offline, "
        "from output/kg_index/ only -- run this before answer for any point this "
        "installation has not already anchored." + _TOOL_DESCRIPTION_SUFFIX),
}

try:
    from mcp.server.fastmcp import FastMCP

    mcp = FastMCP(
        name="floodconnect",
        instructions=(
            "FloodConnect is a read-only flood/canal/pump/tide readout + typology "
            "graph + self-help DAG for Bangkok-area communities (currently Sammakorn, "
            "Ram53)." + _TOOL_DESCRIPTION_SUFFIX
        ),
    )

    @mcp.tool()
    def floodconnect_list_areas() -> dict:
        """List every FloodConnect area this export covers. UNKNOWN is not SAFE. current_local_state and forward_hazard are independent — a
        calm current reading does not cancel an active forecast hazard."""
        return list_areas(_resolve_base())

    @mcp.tool()
    def floodconnect_get_area_state(area_id: str) -> dict:
        """Full current_local_state + forward_hazard for one area. UNKNOWN is not SAFE. current_local_state and forward_hazard are independent
        — a calm current reading does not cancel an active forecast hazard."""
        return get_area_state(_resolve_base(), area_id)

    @mcp.tool()
    def floodconnect_get_station(code: str) -> dict:
        """Look up one canal/water-level station code across all areas.
        UNKNOWN is not SAFE. current_local_state and forward_hazard are
        independent — a calm current reading does not cancel an active
        forecast hazard."""
        return get_station(_resolve_base(), code)

    @mcp.tool()
    def floodconnect_get_typology_subgraph(area_id: str) -> dict:
        """Typology subgraph (nodes/edges) for one area. UNKNOWN is not SAFE. current_local_state and forward_hazard are independent — a
        calm current reading does not cancel an active forecast hazard."""
        return get_typology_subgraph(_resolve_base(), area_id)

    @mcp.tool()
    def floodconnect_find_safe_route(zone_id: str, mode: str, group_size: int) -> dict:
        """Walk the self-help DAG for a verified, fresh route from zone_id.
        UNKNOWN is not SAFE. current_local_state and forward_hazard are
        independent — a calm current reading does not cancel an active
        forecast hazard."""
        return find_safe_route(_resolve_base(), zone_id, mode, group_size)

    @mcp.tool()
    def floodconnect_list_upstream_sources(agency: str | None = None) -> dict:
        """List upstream source-registry entries, optionally filtered by
        agency. UNKNOWN is not SAFE. current_local_state and forward_hazard
        are independent — a calm current reading does not cancel an active
        forecast hazard."""
        return list_upstream_sources(_resolve_base(), agency)

    @mcp.tool()
    def floodconnect_explain_rules() -> dict:
        """Return the fixed epistemic rules this server enforces. UNKNOWN is not SAFE. current_local_state and forward_hazard are independent
        — a calm current reading does not cancel an active forecast hazard."""
        return explain_rules()

    # structured_output=False: a bare `-> dict` return type otherwise makes FastMCP
    # build BOTH an unstructured text block (pydantic_core.to_json(result, indent=2),
    # the whole payload) AND a separate `structuredContent` copy of the SAME payload
    # (wrapped as {"result": ...}) -- a full second serialisation of every field,
    # which is what pushed the real refresh-path MCP response over budget (measured
    # 5,001/5,026 cl100k tokens for sammakorn/ram53, AI.md+SKILL.md+this answer, against
    # the 4,800 ceiling) even though the single JSON text block alone was already under
    # it. No field is dropped by this -- the text content block is the one copy of the
    # answer a client actually needs; it is the duplicate this removes, not any data.
    @mcp.tool(structured_output=False)
    def floodconnect_answer(at: str, offline: bool = False, verbose: bool = False) -> dict:
        """Computes a flood/canal/pump/tide readout for one area (state + hazard +
        accountability + next_action + cctv + source_tags), entirely on THIS machine --
        never a hosted or official reading. By default this FETCHES the relevant wired
        sources first, ONE GET each, using THIS machine's own network/keys (never a
        server we run) -- same as `floodconnect answer --at <at>`. Pass `offline=True`
        to skip that fetch and answer from whatever this machine's own
        data/observations.sqlite already has (FIX D, 2026-10-04: this repo ships NO
        tracked/precomputed snapshot to fall back to -- a point with nothing in the
        local DB yet returns UNKNOWN/OPEN plus a concrete refresh action, never a
        retained value). A failed live fetch likewise falls back only to the stored
        rows already in that local DB, which still pass the single freshness gate
        before deciding anything (stale -> never a colour, never SAFE). `verbose=False`
        (default) caps `state.notes`'s source list to the top sources by this check's
        relevance, keeping the token budget on a populated DB -- pass `verbose=True`
        for the full list.
        UNKNOWN is not SAFE. current_local_state and forward_hazard are independent
        — a calm current reading does not cancel an active forecast hazard."""
        return floodconnect_answer_core(at, offline=offline, verbose=verbose)

    @mcp.tool(structured_output=False)
    def floodconnect_locate(at: str, province: str | None = None) -> dict:
        """KG-first step (M4): resolve a lat,lon point to its province, nearest
        sub-basin(s), nearest assets (gauge/gate/weir/dam/pump_station/tide_gate)
        with their ON_REACH reach, stations sharing that reach/sub-basin,
        responsible agencies, known_gaps, and a compact kg_anchor -- offline,
        from this repo's committed output/kg_index/ only (no network, <3s).
        Pass `province` (code, Thai name, or English name if available) when
        your own geocoding has already decided it -- that gives method="caller".
        Omit it to get up to 3 RELAYED candidates (method="cand"), never a
        single silent guess.
        UNKNOWN is not SAFE. current_local_state and forward_hazard are
        independent — a calm current reading does not cancel an active
        forecast hazard."""
        return floodconnect_locate_core(at, province=province)

    def main() -> None:
        mcp.run("stdio")

except ImportError:
    # Fallback transport used only when the `mcp` SDK is not importable (this
    # repo pins `mcp>=1.2,<2` under the `[mcp]` extra -- see pyproject.toml and
    # README section 7b; the 2.x line renamed the import this module uses,
    # which also lands here). This used to accept
    # `tools/call` directly with no `initialize` handshake and no MCP
    # `content` envelope -- that is not the MCP protocol, so a real MCP
    # client would never get past its own handshake and silently hang or
    # error. A fake-looking success here is worse than a loud failure, so
    # this now implements the minimum real handshake (`initialize` +
    # `notifications/initialized`, a notification that gets NO response per
    # JSON-RPC 2.0) and wraps every `tools/call` result in MCP's
    # `content: [{"type": "text", "text": "<json>"}]` shape, same as the
    # real SDK's FastMCP would produce for a plain dict/str return.
    mcp = None

    _PROTOCOL_VERSION = "2024-11-05"

    _TOOLS = {
        "floodconnect_list_areas": lambda args: list_areas(_resolve_base()),
        "floodconnect_get_area_state": lambda args: get_area_state(_resolve_base(), args["area_id"]),
        "floodconnect_get_station": lambda args: get_station(_resolve_base(), args["code"]),
        "floodconnect_get_typology_subgraph": lambda args: get_typology_subgraph(_resolve_base(), args["area_id"]),
        "floodconnect_find_safe_route": lambda args: find_safe_route(
            _resolve_base(), args["zone_id"], args["mode"], args["group_size"]),
        "floodconnect_list_upstream_sources": lambda args: list_upstream_sources(_resolve_base(), args.get("agency")),
        "floodconnect_explain_rules": lambda args: explain_rules(),
        "floodconnect_answer": lambda args: floodconnect_answer_core(
            args["at"], refresh=args.get("refresh"), offline=args.get("offline", False),
            verbose=args.get("verbose", False)),
        "floodconnect_locate": lambda args: floodconnect_locate_core(
            args["at"], province=args.get("province")),
    }

    def _content_wrap(result: dict) -> dict:
        """Matches the real MCP SDK's tools/call result shape: a `content`
        list of typed blocks, not a bare dict (spec: tools/call result)."""
        return {"content": [{"type": "text", "text": json.dumps(result)}], "isError": False}

    def _content_wrap_error(code: str, message: str) -> dict:
        return {"content": [{"type": "text", "text": json.dumps({"error": {"code": code, "message": message}})}],
                "isError": True}

    def _handle_request(req: dict) -> dict | None:
        """Returns the JSON-RPC response dict, or None for a notification
        (no `id`), which per JSON-RPC 2.0 / MCP gets no response at all --
        `main()` below must not write anything for a None return."""
        method = req.get("method")
        has_id = "id" in req
        if method == "initialize":
            result = {
                "protocolVersion": _PROTOCOL_VERSION,
                "capabilities": {"tools": {}},
                "serverInfo": {"name": "floodconnect", "version": "0.1.4"},
            }
        elif method == "notifications/initialized":
            return None  # notification: no response, by JSON-RPC 2.0 rule
        elif method == "tools/list":
            result = {"tools": [{"name": name, "description": _TOOL_DESCRIPTIONS.get(name, "")}
                                 for name in _TOOLS]}
        elif method == "tools/call":
            params = req.get("params", {})
            name = params.get("name")
            args = params.get("arguments", {})
            fn = _TOOLS.get(name)
            if fn is None:
                result = _content_wrap_error("UNKNOWN_TOOL", f"unknown tool {name!r}")
            else:
                try:
                    result = _content_wrap(fn(args))
                except FloodConnectMCPError as exc:
                    result = _content_wrap_error(exc.code, exc.message)
        else:
            if not has_id:
                return None  # unknown notification: still no response
            return {"jsonrpc": "2.0", "id": req.get("id"),
                    "error": {"code": -32601, "message": f"unknown method {method!r}"}}
        if not has_id:
            return None
        return {"jsonrpc": "2.0", "id": req.get("id"), "result": result}

    def main() -> None:  # pragma: no cover - stdio loop, exercised via _handle_request in tests
        import sys as _sys
        print(
            "floodconnect_mcp: the real `mcp` SDK is not installed in this Python "
            "environment, so this server is running the minimal stdlib JSON-RPC "
            "fallback (handshake + tools only, no resources/prompts/streaming). "
            "Run `pip install -e '.[mcp]'` in this clone's venv for the full MCP "
            "server. Continuing in fallback mode.",
            file=_sys.stderr,
        )
        for line in _sys.stdin:
            line = line.strip()
            if not line:
                continue
            try:
                req = json.loads(line)
            except json.JSONDecodeError:
                continue
            resp = _handle_request(req)
            if resp is None:
                continue
            _sys.stdout.write(json.dumps(resp) + "\n")
            _sys.stdout.flush()


if __name__ == "__main__":
    main()
